import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  {
    // Convex bundles these folders with its own tsconfig, which has no "@/*" alias.
    // Relative imports keep the shared domain code loadable from convex/ functions.
    files: ["domain/**", "convex/**", "adapters/**", "utils/**"],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          patterns: [
            {
              group: ["@/*"],
              message:
                "Use a relative import here: Convex bundles this file without the root tsconfig paths.",
            },
          ],
        },
      ],
    },
  },
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by `npx convex dev` / `npx convex codegen`.
    "convex/_generated/**",
  ]),
]);

export default eslintConfig;
