export const API_ENDPOINTS = {
  PRICES: "/api/prices",
} as const;

export const API_ERROR_CODES = [
  "INVALID_SYMBOLS",
  "INVALID_YEAR",
  "RATE_LIMITED",
  "PRICES_UNAVAILABLE",
  "PRICE_HISTORY_UNAVAILABLE",
  "CONFIGURATION_ERROR",
  "UPSTREAM_ERROR",
  "INTERNAL_ERROR",
] as const;
